services:
  vue:
    image: node:20-alpine
    container_name: vue-dev
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
      - "3000:3000" # backend
    command: sh -c "npm install && node js/server.js & npm run dev"
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
